import Head from 'next/head'
import Button from '@mui/material/Button'
import { Box, useTheme } from '@mui/material'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  const themes = useTheme()
  console.log(`themes :`, themes)

  return (
    <>
      <Head>
        <title>Course NextJs Udemy</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Button variant='contained'>Hello world</Button>
      <Box sx={{ m: 6 }}>
        <CustomTextField label='Email' />
      </Box>
    </>
  )
}
